[구글 코랩(Colab)에서 실행하기](https://colab.research.google.com/github/lovedlim/bigdata_analyst_cert_v2/blob/main/part4/ch8/p8_type1.ipynb)

## 작업형1

### 문제1

제공된 데이터셋(df)을 활용하여 대륙별(continent) 맥주 소비량(beer_servings)의 평균을 구하고, 평균 맥주 소비량이 가장 높은 대륙을 찾으시오. 이후 해당 대륙에 속한 국가들의 데이터를 추출하여 맥주 소비량을 기준으로 내림차순 정렬했을 때, 상위 5번째에 위치한 국가의 맥주 소비량 값을 정수 형태로 제출하시오.

In [16]:
continent = df.groupby('continent')['beer_servings'].mean().idxmax()
continent
print(df[df['continent'] == continent]['beer_servings'].sort_values(ascending = False))
result = df[df['continent'] == continent]['beer_servings'].sort_values(ascending = False).iloc[4]
print(result)

45     361
65     346
98     343
135    343
81     313
140    297
16     295
160    284
151    283
93     281
9      279
156    270
60     263
120    251
3      245
99     236
75     234
76     233
25     231
42     230
48     224
57     224
182    219
180    206
155    196
136    194
44     192
166    185
126    169
165    152
105    149
15     142
67     133
61     127
139    109
170    106
1       89
83      85
21      76
64      52
113     31
7       21
10      21
111      0
147      0
Name: beer_servings, dtype: int64
313

In [1]:
import pandas as pd
# df = pd.read_csv("drinks.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch8/drinks.csv")
df

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
0,Afghanistan,0,0,0,0.0,Asia
1,Albania,89,132,54,4.9,Europe
2,Algeria,25,0,14,0.7,Africa
3,Andorra,245,138,312,12.4,Europe
4,Angola,217,57,45,5.9,Africa
...,...,...,...,...,...,...
188,Venezuela,333,100,3,7.7,South America
189,Vietnam,111,2,1,2.0,Asia
190,Yemen,6,0,0,0.1,Asia
191,Zambia,32,19,4,2.5,Africa
192,Zimbabwe,64,18,4,4.7,Africa

In [ ]:
import pandas as pd
# df = pd.read_csv("drinks.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch8/drinks.csv")

# 1) 대륙별 맥주 소비량의 평균
continent = df.groupby("continent")['beer_servings'].mean() # Europe
top_continent = continent.idxmax()

# 2) 국가별 맥주 소비량
cond = df['continent'] == top_continent
df = df[cond]
df = df.sort_values('beer_servings', ascending=False)
df.iloc[4, 1] # 또는 df.iloc[4]['beer_servings']

313

### 문제2

제공된 데이터셋(df)에서 각 행의 관광, 공무, 사업, 기타 컬럼 값을 모두 더하여 '방문객합계' 파생변수를 생성하고, 관광 / 방문객합계 수식을 사용하여 '관광객비율' 파생변수를 추가로 생성하시오. 이후 아래 두 조건에 따라 각각 값을 구한 뒤, 두 값의 합($A + B$)을 계산하여 정수 형태로 제출하시오.

값 A: '관광객비율'을 기준으로 내림차순 정렬했을 때, 상위 2번째 행의 '사업' 방문객 수

값 B: '관광' 방문객 수를 기준으로 내림차순 정렬했을 때, 상위 2번째 행의 '공무' 방문객 수

In [23]:
df['방문객합계'] = df.iloc[:, 1:].sum(axis = 1)
df.head()

    나라    관광   공무   사업   기타  방문객합계
0  국가1  1184  270  380   55   1889
1  국가2  1059  184  267   86   1596
2  국가3  1129  168  261   50   1608
3  국가4   692  106  214  125   1137
4  국가5  1335  296  296   84   2011

In [24]:
df['관광객비율'] = df['관광'] / df['방문객합계']
df

       나라    관광   공무   사업   기타  방문객합계     관광객비율
0     국가1  1184  270  380   55   1889  0.626787
1     국가2  1059  184  267   86   1596  0.663534
2     국가3  1129  168  261   50   1608  0.702114
3     국가4   692  106  214  125   1137  0.608619
4     국가5  1335  296  296   84   2011  0.663849
..    ...   ...  ...  ...  ...    ...       ...
95   국가96   898  119  244  132   1393  0.644652
96   국가97  1111  195  234  118   1658  0.670084
97   국가98  1065  172  362   72   1671  0.637343
98   국가99  1408  254  288  149   2099  0.670796
99  국가100  1133  294  233  133   1793  0.631902

[100 rows x 7 columns]

In [45]:
df2 = df.sort_values(by = '관광객비율', ascending = False)['사업']
A = df2.iloc[1] # 중요

B = df.sort_values(by = '관광', ascending = False)['공무'].iloc[1]
print(A, B, A +B)

203 238 441

In [17]:
# 방법1
import pandas as pd
# df = pd.read_csv("tourist.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch8/tourist.csv")
df

       나라    관광   공무   사업   기타
0     국가1  1184  270  380   55
1     국가2  1059  184  267   86
2     국가3  1129  168  261   50
3     국가4   692  106  214  125
4     국가5  1335  296  296   84
..    ...   ...  ...  ...  ...
95   국가96   898  119  244  132
96   국가97  1111  195  234  118
97   국가98  1065  172  362   72
98   국가99  1408  254  288  149
99  국가100  1133  294  233  133

[100 rows x 5 columns]

In [ ]:
# 방법1
import pandas as pd
# df = pd.read_csv("tourist.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch8/tourist.csv")

# 1) 방문객 합계 및 관관객 비율 계산
df['방문객합계'] = df['관광'] + df['공무'] + df['사업'] + df['기타']
df['관광객비율'] = df['관광'] / df['방문객합계']

# 2) 조건에 맞는 값 찾기
a = df.sort_values('관광객비율', ascending=False).iloc[1, 3] # 또는 iloc[1]['사업']
b = df.sort_values('관광', ascending=False).iloc[1, 2] # 또는 iloc[1]['공무']

print(a+b)

441

In [ ]:
# 방법2
import pandas as pd
# df = pd.read_csv("tourist.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch8/tourist.csv")

# 1) 방문객 합계 및 관관객 비율 계산
df['방문객합계'] = df['관광'] + df['공무'] + df['사업'] + df['기타']
df['관광객비율'] = df['관광'] / df['방문객합계']

# 2) 조건에 맞는 값 찾기
a = df.nlargest(2, '관광객비율').iloc[1]['사업']
b = df.nlargest(2, '관광').iloc[1]['공무']

print(a+b)

441

### 문제3

제공된 데이터셋(df)의 co 컬럼과 nmhc 컬럼에 대해 각각 Min-Max 스케일링(정규화)을 수행하여 0과 1 사이의 값으로 변환하시오. 변환된 두 컬럼의 표준편차를 각각 계산한 후, co 스케일링 값의 표준편차에서 nmhc 스케일링 값의 표준편차를 뺀 차이값을 구하시오. 최종 결과는 소수점 셋째 자리까지 반올림한 실수 형태로 제출하시오.

In [51]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch8/chem.csv")
df

   sample   co  nmhc  etc
0     샘플1   79    54   31
1     샘플2   84    57   58
2     샘플3  109    74  113
3     샘플4   15    77   21
4     샘플5   65    77  115
..    ...  ...   ...  ...
95   샘플96   56    58   86
96   샘플97   33    59  111
97   샘플98   55    79  105
98   샘플99   69    51   59
99  샘플100   94    45   59

[100 rows x 4 columns]

In [53]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
print(df.head())
df['co'] = scaler.fit_transform(df[['co']])
df['nmhc'] = scaler.fit_transform(df[['nmhc']])
print(df.head())
#print(help(MinMaxScaler))

  sample   co  nmhc  etc
0    샘플1   79    54   31
1    샘플2   84    57   58
2    샘플3  109    74  113
3    샘플4   15    77   21
4    샘플5   65    77  115
  sample        co      nmhc  etc
0    샘플1  0.680851  0.500000   31
1    샘플2  0.734043  0.534091   58
2    샘플3  1.000000  0.727273  113
3    샘플4  0.000000  0.761364   21
4    샘플5  0.531915  0.761364  115

In [56]:
std_co = df['co'].std()
std_nmhc = df['nmhc'].std()
result = std_co- std_nmhc
print(round(result, 3))

-0.017

In [ ]:
# 방법1
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

# df = pd.read_csv("chem.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch8/chem.csv")

# 1) Min-Max 스케일링 (데이터프레임으로 만들기)
scaler = MinMaxScaler()
df['co_scaled'] = scaler.fit_transform(df[['co']])
df['nmhc_scaled'] = scaler.fit_transform(df[['nmhc']])

# 2) 표준편차 계산 (판다스 표준편차)
co_std = df['co_scaled'].std()
nmhc_std = df['nmhc_scaled'].std()
print(co_std, nmhc_std)

# 3) 표준편차 차이 계산 및 반올림
std_diff = round(co_std - nmhc_std, 3)
print(std_diff)

0.2856516497116944 0.3030617020578397
-0.017

In [ ]:
# 방법2
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

# df = pd.read_csv("chem.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch8/chem.csv")

# 1) Min-Max 스케일링 (transform의 결과는 넘파이)
scaler = MinMaxScaler()
co_scaled = scaler.fit_transform(df[['co']])
nmhc_scaled = scaler.fit_transform(df[['nmhc']])

# 2) 표준편차 계산 (넘파이 표준편차)
co_std = co_scaled.std()
nmhc_std = nmhc_scaled.std()
print(co_std, nmhc_std)

# 3) 표준편차 차이 계산 및 반올림
std_diff = round(co_std - nmhc_std, 3)
print(std_diff)

0.2842198028519168 0.3015425862157
-0.017