[구글 코랩(Colab)에서 실행하기](https://colab.research.google.com/github/lovedlim/bigdata_analyst_cert_v2/blob/main/part4/ch8/p8_type3.ipynb)

## 작업형3

### 문제1-1

제공된 데이터를 바탕으로 Churn을 종속변수로 하고, 나머지 10개 변수 전체를 독립변수로 설정하여 로지스틱 회귀분석을 수행하시오. 분석 결과에서 상수항(Intercept)을 제외하고 유의수준 5%($\alpha = 0.05$) 하에서 통계적으로 유의하지 않은(p-value > 0.05) 독립변수의 총 개수를 구하시오.

In [4]:
import pandas as pd
# df = pd.read_csv("churn.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch8/churn.csv")
df

,Churn,AccountWeeks,ContractRenewal,DataPlan,DataUsage,CustServCalls,DayMins,DayCalls,MonthlyCharge,OverageFee,RoamMins
0,0,51,1,0,1.0,0,303.7,83,72.5,9.3,3.8
1,1,61,1,0,-0.2,2,194.8,89,66.3,10.9,13.3
2,0,84,1,1,-1.3,2,157.6,109,35.7,10.0,12.5
3,0,65,1,0,1.0,1,223.1,129,64.2,9.1,5.1
4,0,154,1,0,1.0,0,137.0,115,40.0,7.7,4.6
...,...,...,...,...,...,...,...,...,...,...,...
995,0,32,1,0,0.6,1,241.2,94,64.1,8.5,13.4
996,0,24,0,0,-1.1,1,155.2,97,48.5,9.8,8.3
997,0,67,1,0,1.9,3,184.6,69,45.8,7.3,8.5
998,0,72,1,0,1.0,0,153.2,65,34.8,9.6,14.5
999,0,116,1,0,0.8,0,207.6,110,46.4,10.9,11.8

In [8]:
import statsmodels.formula.api as smf

formula = "Churn ~ AccountWeeks + ContractRenewal + DataPlan + DataUsage + CustServCalls + DayMins + DayCalls + MonthlyCharge + OverageFee + RoamMins "
model = smf.logit(formula, data = df).fit()
print(model.summary())
print((model.pvalues[1:] > 0.05).sum())

Optimization terminated successfully.
         Current function value: 0.393603
         Iterations 6
                           Logit Regression Results
==============================================================================
Dep. Variable:                  Churn   No. Observations:                 1000
Model:                          Logit   Df Residuals:                      989
Method:                           MLE   Df Model:                           10
Date:                Tue, 16 Jun 2026   Pseudo R-squ.:                 0.02367
Time:                        13:03:44   Log-Likelihood:                -393.60
converged:                       True   LL-Null:                       -403.14
Covariance Type:            nonrobust   LLR p-value:                   0.03924
===================================================================================
                      coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------
Intercept          -2.2146      0.913     -2.425      0.015      -4.005      -0.424
AccountWeeks        0.0026      0.002      1.114      0.265      -0.002       0.007
ContractRenewal     0.1603      0.325      0.493      0.622      -0.477       0.798
DataPlan            0.2874      0.198      1.454      0.146      -0.100       0.675
DataUsage          -0.1698      0.072     -2.343      0.019      -0.312      -0.028
CustServCalls       0.1374      0.074      1.858      0.063      -0.008       0.282
DayMins            -0.0036      0.002     -2.092      0.036      -0.007      -0.000
DayCalls            0.0023      0.004      0.526      0.599      -0.006       0.011
MonthlyCharge       0.0042      0.005      0.778      0.436      -0.006       0.015
OverageFee         -0.0127      0.036     -0.352      0.725      -0.084       0.058
RoamMins            0.0098      0.034      0.292      0.770      -0.056       0.076
===================================================================================
8

In [ ]:
import pandas as pd
# df = pd.read_csv("churn.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch8/churn.csv")

# 1) 로지스틱 회귀분석을 위한 포뮬라 생성
formula = "Churn ~ AccountWeeks + ContractRenewal + DataPlan + DataUsage + CustServCalls + DayMins + DayCalls + MonthlyCharge + OverageFee + RoamMins"

# 2) 로지스틱 회귀 모델 생성 및 학습
from statsmodels.formula.api import logit
model = logit(formula, data=df).fit()

# 3) 유의하지 않은 독립변수의 개수 구하기
print(model.summary())
sum(model.pvalues[1:] > 0.05) # Intercept는 독립변수가 아니므로 제외

Optimization terminated successfully.
         Current function value: 0.393603
         Iterations 6
                           Logit Regression Results
==============================================================================
Dep. Variable:                  Churn   No. Observations:                 1000
Model:                          Logit   Df Residuals:                      989
Method:                           MLE   Df Model:                           10
Date:                Mon, 17 Mar 2025   Pseudo R-squ.:                 0.02367
Time:                        03:48:00   Log-Likelihood:                -393.60
converged:                       True   LL-Null:                       -403.14
Covariance Type:            nonrobust   LLR p-value:                   0.03924
===================================================================================
                      coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------
Intercept          -2.2146      0.913     -2.425      0.015      -4.005      -0.424
AccountWeeks        0.0026      0.002      1.114      0.265      -0.002       0.007
ContractRenewal     0.1603      0.325      0.493      0.622      -0.477       0.798
DataPlan            0.2874      0.198      1.454      0.146      -0.100       0.675
DataUsage          -0.1698      0.072     -2.343      0.019      -0.312      -0.028
CustServCalls       0.1374      0.074      1.858      0.063      -0.008       0.282
DayMins            -0.0036      0.002     -2.092      0.036      -0.007      -0.000
DayCalls            0.0023      0.004      0.526      0.599      -0.006       0.011
MonthlyCharge       0.0042      0.005      0.778      0.436      -0.006       0.015
OverageFee         -0.0127      0.036     -0.352      0.725      -0.084       0.058
RoamMins            0.0098      0.034      0.292      0.770      -0.056       0.076
===================================================================================

8

### 문제1-2

[문제 1-1]의 결과 중 유의한 변수로 제시된 독립변수들 중 DataUsage와 DayMins 두 개 변수만을 독립변수로 지정하여 로지스틱 회귀 모델을 재학습시키시오. 재구축된 모델의 상수항(Intercept)을 포함한 모든 회귀계수(Coef)의 합계를 구하시오.

In [10]:
formula2 = "Churn ~ DataUsage + DayMins"
model = smf.logit(formula2, data = df).fit()

print(round(model.params.sum(),3))

Optimization terminated successfully.
         Current function value: 0.397599
         Iterations 6
-1.213

In [ ]:
# 1) 유의한 변수 선택
print(model.pvalues < 0.05)
formula = "Churn ~ DataUsage + DayMins"

# 2) 로지스틱 회귀
model = logit(formula, data=df).fit()

# 3) 유의한 회귀계수 합계
print(model.summary())
round(sum(model.params),3)

Intercept           True
AccountWeeks       False
ContractRenewal    False
DataPlan           False
DataUsage           True
CustServCalls      False
DayMins             True
DayCalls           False
MonthlyCharge      False
OverageFee         False
RoamMins           False
dtype: bool
Optimization terminated successfully.
         Current function value: 0.397599
         Iterations 6
                           Logit Regression Results
==============================================================================
Dep. Variable:                  Churn   No. Observations:                 1000
Model:                          Logit   Df Residuals:                      997
Method:                           MLE   Df Model:                            2
Date:                Mon, 17 Mar 2025   Pseudo R-squ.:                 0.01375
Time:                        03:48:01   Log-Likelihood:                -397.60
converged:                       True   LL-Null:                       -403.14
Covariance Type:            nonrobust   LLR p-value:                  0.003908
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     -1.0395      0.303     -3.434      0.001      -1.633      -0.446
DataUsage     -0.1697      0.071     -2.376      0.017      -0.310      -0.030
DayMins       -0.0039      0.002     -2.264      0.024      -0.007      -0.001
==============================================================================

-1.213

### 문제1-3

[문제 1-2]에서 재학습시킨 로지스틱 회귀 모델을 바탕으로, 다른 모든 조건이 동일할 때 DataUsage(데이터 사용량)가 5단위 증가할 때의 오즈비(Odds Ratio, 승산비)를 구하시오.

출력 형식: 소수점 셋째 자리까지 반올림 (예: 0.456)

In [13]:
import numpy as np
coef = model.params['DataUsage']
print(round(np.exp(coef*5),3))
# params(회귀계수) 값에 * 5(단위)

0.428

In [ ]:
# 1) 변수의 회귀계수 추출
import numpy as np
coef = model.params['DataUsage']

# 2) 오즈비 계산
round(np.exp(coef * 5),3)

0.428

### 문제2-1

제공된 데이터를 바탕으로 PIQ를 종속변수로 하고, Brain, Height, Weight를 독립변수로 설정하여 다중선형회귀분석을 수행하시오. 상수항(Intercept)을 제외한 독립변수 중 p-value(유의확률)가 가장 작은(가장 유의한) 변수의 회귀계수(Coef)를 구하시오.

출력 형식: 소수점 셋째 자리까지 반올림 (예: 2.343)

In [27]:
import pandas as pd
# df = pd.read_csv("piq.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch8/piq.csv")
df.head()

   PIQ  Brain  Height  Weight
0  132  85.78    62.5     127
1   96  86.54    68.0     135
2   84  90.49    66.3     134
3  134  79.06    62.0     122
4   86  88.91    70.0     180

In [26]:
import statsmodels.formula.api as smf
formula = "PIQ ~ Brain + Height + Weight"
model = smf.ols(formula, data =df).fit()
print(model.summary())
idx = model.pvalues[1:].idxmin()

print(round(model.params[idx],3))

                            OLS Regression Results
==============================================================================
Dep. Variable:                    PIQ   R-squared:                       0.370
Model:                            OLS   Adj. R-squared:                  0.329
Method:                 Least Squares   F-statistic:                     9.024
Date:                Tue, 16 Jun 2026   Prob (F-statistic):           8.25e-05
Time:                        13:15:29   Log-Likelihood:                -217.27
No. Observations:                  50   AIC:                             442.5
Df Residuals:                      46   BIC:                             450.2
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     74.5114     50.564      1.474      0.147     -27.269     176.292
Brain          2.3431      0.456      5.141      0.000       1.426       3.261
Height        -2.6444      1.064     -2.485      0.017      -4.786      -0.503
Weight         0.0406      0.167      0.243      0.809      -0.296       0.377
==============================================================================
Omnibus:                        8.608   Durbin-Watson:                   2.386
Prob(Omnibus):                  0.014   Jarque-Bera (JB):                2.629
Skew:                           0.041   Prob(JB):                        0.269
Kurtosis:                       1.880   Cond. No.                     3.48e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.48e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
2.343

In [ ]:
df.head()

   PIQ  Brain  Height  Weight
0  132  85.78    62.5     127
1   96  86.54    68.0     135
2   84  90.49    66.3     134
3  134  79.06    62.0     122
4   86  88.91    70.0     180

In [ ]:
# 1) 다중 선형 회귀 분석
from statsmodels.formula.api import ols
model = ols('PIQ ~ Brain + Height + Weight', data=df).fit()

# 2) 가장 작은 p-value를 가진 변수의 회귀계수 찾기
print(model.summary())

# 정답: 2.343

                            OLS Regression Results
==============================================================================
Dep. Variable:                    PIQ   R-squared:                       0.370
Model:                            OLS   Adj. R-squared:                  0.329
Method:                 Least Squares   F-statistic:                     9.024
Date:                Mon, 17 Mar 2025   Prob (F-statistic):           8.25e-05
Time:                        03:48:01   Log-Likelihood:                -217.27
No. Observations:                  50   AIC:                             442.5
Df Residuals:                      46   BIC:                             450.2
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     74.5114     50.564      1.474      0.147     -27.269     176.292
Brain          2.3431      0.456      5.141      0.000       1.426       3.261
Height        -2.6444      1.064     -2.485      0.017      -4.786      -0.503
Weight         0.0406      0.167      0.243      0.809      -0.296       0.377
==============================================================================
Omnibus:                        8.608   Durbin-Watson:                   2.386
Prob(Omnibus):                  0.014   Jarque-Bera (JB):                2.629
Skew:                           0.041   Prob(JB):                        0.269
Kurtosis:                       1.880   Cond. No.                     3.48e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.48e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

### 문제 2-2

[문제 2-1]에서 학습시킨 다중선형회귀 모델의 결정계수(R-squared, 설명력)를 구하시오.

In [35]:
print(round(model.rsquared,3))

0.37

In [ ]:
# 1) 결정계수(R-squared) 값
print(round(model.rsquared,3))

0.37

### 문제 2-3

[문제 2-1]에서 학습시킨 회귀 모델을 사용하여 새로운 데이터인 Brain=90, Height=70, Weight=150인 조건의 PIQ 예측값을 구하고, 이를 반올림하여 정수 형태로 제출하시오.

In [40]:
new_data = pd.DataFrame({'Brain' : [90], 'Height' : [70],'Weight' : [150]})
pred = model.predict(new_data)
print(pred)
print(round(pred[0],0))

0    106.38302
dtype: float64
106.0

In [ ]:
# 1) 새로운 데이터 생성
new_data = pd.DataFrame({'Brain': [90], 'Height': [70], 'Weight': [150]})

# 2) PIQ 예측
pred = model.predict(new_data)
print(pred)
print(round(pred[0]))

0    106.38302
dtype: float64
106