[구글 코랩(Colab)에서 실행하기](https://colab.research.google.com/github/lovedlim/bae-v3/blob/main/part4/ch10/p10_type3.ipynb)

## 작업형3

문제 1-1. 회귀계수 구하기

로지스틱 회귀모형을 적합한 후, 독립변수 중 **월 소득(income) 변수의 회귀계수(Coefficient)**를 구하시오.

정답은 소수점 넷째 자리에서 반올림하여 소수점 셋째 자리까지 출력하시오.

In [1]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bae-v3/main/part4/ch10/attrition.csv")
df

      attrition  age  income  overtime
0             0   44    6467         1
1             0   41    6201         0
2             1   25    4017         1
3             0   28    6360         1
4             1   58    2369         0
...         ...  ...     ...       ...
5995          1   25    2950         1
5996          1   56    5786         0
5997          1   53    5884         0
5998          1   38    3897         0
5999          1   49    2556         0

[6000 rows x 4 columns]

In [16]:
from statsmodels.formula.api import logit
formula = "attrition ~ age + income +  overtime"
model = logit(formula, data = df).fit()
#print(model.summary())
print(round(model.params['income'],3))
#print(help(model))

Optimization terminated successfully.
         Current function value: 0.387298
         Iterations 7
-0.002

In [10]:
import statsmodels.formula.api as smf
print(dir(smf))

['PytestTester', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'formulatools', 'handle_formula_data', 'test']

### 문제1-1

In [ ]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bae-v3/main/part4/ch10/attrition.csv")

# 1) 로지스틱 회귀분석 수행
from statsmodels.formula.api import logit
model = logit("attrition ~ age + income + overtime", data=df).fit()

# 2) 회귀 분석 결과 출력
print(model.summary())

# 3) income 회귀계수 출력
print(round(model.params["income"], 3))

# 정답: -0.002

Optimization terminated successfully.
         Current function value: 0.387298
         Iterations 7
                           Logit Regression Results
==============================================================================
Dep. Variable:              attrition   No. Observations:                 6000
Model:                          Logit   Df Residuals:                     5996
Method:                           MLE   Df Model:                            3
Date:                Wed, 07 Jan 2026   Pseudo R-squ.:                  0.4215
Time:                        07:26:53   Log-Likelihood:                -2323.8
converged:                       True   LL-Null:                       -4016.9
Covariance Type:            nonrobust   LLR p-value:                     0.000
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      7.7724      0.246     31.650      0.000       7.291       8.254
age           -0.0044      0.004     -1.208      0.227      -0.012       0.003
income        -0.0015   3.66e-05    -41.263      0.000      -0.002      -0.001
overtime       0.0397      0.074      0.537      0.592      -0.105       0.185
==============================================================================
-0.002

### 문제1-2

문제 1-2. 오즈비(Odds Ratio) 계산하기

로지스틱 회귀모형에서 다른 독립변수들이 고정되어 있을 때, **나이(age)가 1단위 증가할 때의 오즈비(Odds Ratio)**를 구하시오.

정답은 소수점 넷째 자리에서 반올림하여 소수점 셋째 자리까지 출력하시오

In [19]:
import numpy as np
print(round(np.exp(model.params['age']),3))

0.996

In [ ]:
# 1) 오즈비 계산
import numpy as np
result = np.exp(model.params["age"])

# 2) 반올림 후 결과 출력
print(round(result, 3))

# 정답: 0.996

0.996

### 문제1-3

문제 1-3. 새로운 데이터 예측하기

구축된 회귀모형을 바탕으로 나이가 40세이고, 월 소득이 4500이며, 시간 외 근무를 하는(overtime=1) 새로운 직원이 주어졌을 때, 이 직원이 **이직할 확률(P)**을 예측하시오.

정답은 소수점 넷째 자리에서 반올림하여 소수점 셋째 자리까지 출력하시오.

In [26]:
new_data = pd.DataFrame({'age': [40], 'income' : [4500], 'overtime' : [1]})
print(new_data)

   age  income  overtime
0   40    4500         1

In [28]:
pred = model.predict(new_data)
print(round(pred,3))

0    0.697
dtype: float64

In [ ]:
# 1) 새로운 직원 데이터 만들기
new = pd.DataFrame({"age":[40], "income":[4500], "overtime":[1]})

# 2) 예측
pred = model.predict(new)

# 3) 반올림 후 결과 출력
print(round(pred[0], 3))

0.697

### 문제2-1

2-1. 회귀계수 계산 및 합 구하기

독립변수로 외벽 면적(wall), 지붕 면적(roof), 유리창 면적(glazing), 건물의 높이(height)를 사용하여 다중 선형 회귀모형을 적합한 후, 절편(Intercept)을 제외한 모든 독립변수들의 회귀계수(Coefficient)의 합을 구하시오.

정답은 소수점 넷째 자리에서 반올림하여 소수점 셋째 자리까지 출력하시오.

In [29]:
import pandas as pd
import numpy as np
import statsmodels.formula.api as smf
print(dir(smf))

['__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'conditional_logit', 'conditional_mnlogit', 'conditional_poisson', 'gee', 'glm', 'glmgam', 'gls', 'glsar', 'logit', 'mixedlm', 'mnlogit', 'negativebinomial', 'nominal_gee', 'ols', 'ordinal_gee', 'phreg', 'poisson', 'probit', 'quantreg', 'rlm', 'wls']

In [31]:
# 1) 데이터 불러오기
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bae-v3/main/part4/ch10/heating.csv")
df

     heating_load  wall   roof  glazing  height
0            84.7  23.6  170.2     39.1     6.2
1            98.4  27.9  159.3     40.6     6.0
2            69.0  22.6  100.0     20.7     8.3
3            74.5  21.5  116.8     29.8     7.1
4            85.5  36.3  160.3     11.5     5.1
..            ...   ...    ...      ...     ...
545          79.5  35.8  100.2     47.2    12.2
546          87.3  23.9  177.6     21.1     5.4
547          78.8  31.8  145.8     23.0    10.2
548          71.2  27.3  102.5     43.4    13.5
549          79.9  33.9  177.9     46.7     4.7

[550 rows x 5 columns]

In [41]:
formula2 = "heating_load ~ wall + roof + glazing + height"
model2 = smf.ols(formula2, data = df).fit()
#print(model2.summary())
print(round(model2.params[1:].sum(),3))

0.254

In [ ]:
import pandas as pd

# 1) 데이터 불러오기
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bae-v3/main/part4/ch10/heating.csv")

# 2) 다중선형회귀분석
from statsmodels.formula.api import ols
model = ols("heating_load ~ wall + roof + glazing + height", data=df).fit()

# 3) 회귀 분석 결과 출력
print(model.summary())

# 4) 절편 제외 회귀계수들의 합 구하기
result = model.params[1:].sum()
print(round(result, 3))

# 정답: 0.254

                            OLS Regression Results
==============================================================================
Dep. Variable:           heating_load   R-squared:                       0.754
Model:                            OLS   Adj. R-squared:                  0.752
Method:                 Least Squares   F-statistic:                     417.8
Date:                Wed, 07 Jan 2026   Prob (F-statistic):          2.02e-164
Time:                        07:26:53   Log-Likelihood:                -1772.0
No. Observations:                 550   AIC:                             3554.
Df Residuals:                     545   BIC:                             3576.
Df Model:                           4
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     38.3821      1.504     25.517      0.000      35.427      41.337
wall           0.0304      0.030      1.012      0.312      -0.029       0.090
roof           0.2483      0.006     39.564      0.000       0.236       0.261
glazing        0.2217      0.023      9.693      0.000       0.177       0.267
height        -0.2469      0.077     -3.212      0.001      -0.398      -0.096
==============================================================================
Omnibus:                        0.698   Durbin-Watson:                   1.896
Prob(Omnibus):                  0.705   Jarque-Bera (JB):                0.785
Skew:                          -0.077   Prob(JB):                        0.675
Kurtosis:                       2.899   Cond. No.                         805.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
0.254

### 문제2-2

2-2. 변수 제거 후 결정계수($R^2$)
 확인하기

 기존 모형에서 독립변수 중 외벽 면적(wall) 변수를 제거하고, 종속변수 heating_load에 대해 나머지 3개 변수(roof, glazing, height)만을 사용하여 다중 선형 회귀모형을 다시 적합하시오. 이때 변경된 모형의 **결정계수(R-squared)**를 구하시오.

 정답은 소수점 넷째 자리에서 반올림하여 소수점 셋째 자리까지 출력하시오.

In [46]:
new_formula2 = "heating_load ~ roof + glazing + height"
new_model2 = smf.ols(new_formula2, data = df).fit()
print(new_model2.summary())
print(round(new_model2.rsquared,3))

                            OLS Regression Results
==============================================================================
Dep. Variable:           heating_load   R-squared:                       0.754
Model:                            OLS   Adj. R-squared:                  0.752
Method:                 Least Squares   F-statistic:                     556.7
Date:                Mon, 15 Jun 2026   Prob (F-statistic):          1.31e-165
Time:                        08:34:40   Log-Likelihood:                -1772.5
No. Observations:                 550   AIC:                             3553.
Df Residuals:                     546   BIC:                             3570.
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     39.2337      1.247     31.467      0.000      36.784      41.683
roof           0.2480      0.006     39.559      0.000       0.236       0.260
glazing        0.2210      0.023      9.668      0.000       0.176       0.266
height        -0.2500      0.077     -3.255      0.001      -0.401      -0.099
==============================================================================
Omnibus:                        0.592   Durbin-Watson:                   1.896
Prob(Omnibus):                  0.744   Jarque-Bera (JB):                0.661
Skew:                          -0.075   Prob(JB):                        0.718
Kurtosis:                       2.920   Cond. No.                         658.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
0.754

In [ ]:
# 1) 다시 회귀 분석
model = ols("heating_load ~ roof + glazing + height", data=df).fit()

# 2) 결정계수(R-squared) 확인
print(model.summary())

# 정답: 0.754

                            OLS Regression Results
==============================================================================
Dep. Variable:           heating_load   R-squared:                       0.754
Model:                            OLS   Adj. R-squared:                  0.752
Method:                 Least Squares   F-statistic:                     556.7
Date:                Wed, 07 Jan 2026   Prob (F-statistic):          1.31e-165
Time:                        07:26:54   Log-Likelihood:                -1772.5
No. Observations:                 550   AIC:                             3553.
Df Residuals:                     546   BIC:                             3570.
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     39.2337      1.247     31.467      0.000      36.784      41.683
roof           0.2480      0.006     39.559      0.000       0.236       0.260
glazing        0.2210      0.023      9.668      0.000       0.176       0.266
height        -0.2500      0.077     -3.255      0.001      -0.401      -0.099
==============================================================================
Omnibus:                        0.592   Durbin-Watson:                   1.896
Prob(Omnibus):                  0.744   Jarque-Bera (JB):                0.661
Skew:                          -0.075   Prob(JB):                        0.718
Kurtosis:                       2.920   Cond. No.                         658.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

### 문제2-3

2-3. 새로운 데이터 예측하기

문제 2-2에서 구축한 수정된 회귀모형을 바탕으로 외벽 면적(wall)이 20, 지붕 면적(roof)이 150, 유리창 면적(glazing)이 20, 건물의 높이(height)가 5인 새로운 건물이 주어졌을 때, 이 건물의 난방 부하(heating_load) 예측값을 구하시오.

정답은 소수점 넷째 자리에서 반올림하여 소수점 셋째 자리까지 출력하시오

In [47]:
new_data2 = pd.DataFrame({"wall": [20], "roof": [150], "glazing": [20], "height": [5]})
print(new_data2)

   wall  roof  glazing  height
0    20   150       20       5

In [50]:
pred2 = new_model2.predict(new_data2)
print(round(pred2,3))

0    79.612
dtype: float64

In [ ]:
# 1) 새로운 데이터 (예: 문제에서 제시된 값)
new = pd.DataFrame({"wall":[20],"roof":[150],"glazing":[20],"height":[5]})

# 2) 예측값 계산
pred = model.predict(new)

# 3) 반올림 후 출력
print(round(pred[0], 3))

# 정답: 79.612

79.612