[구글 코랩(Colab)에서 실행하기](https://colab.research.google.com/github/lovedlim/bigdata_analyst_cert_v2/blob/main/part4/ch6/p6_type1.ipynb)

## 작업형1

### 문제1

제공된 데이터셋(df)의 출동시간과 도착시간 컬럼을 활용하여 출동 후 도착까지 걸린 '시간차이(단위: 분)'를 파생변수로 생성하시오. 이후 소방서별 평균 시간차이를 계산하고, 평균 시간차이가 가장 큰(가장 오래 걸린) 소방서의 평균 시간을 반올림하여 정수 형태로 제출하시오.

In [26]:
df['출동시간'] = pd.to_datetime(df['출동시간'])
df['도착시간'] = pd.to_datetime(df['도착시간'])

df['시간차이(단위: 분)'] = ((df['도착시간']-df['출동시간']).dt.total_seconds())/60

result = df.groupby('소방서')['시간차이(단위: 분)'].mean().max()
print(round(result))

81

In [1]:
import pandas as pd
# df = pd.read_csv("data6-1-1.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch6/data6-1-1.csv")
df

     소방서                 출동시간                 도착시간
0   소방서1  2023-09-16 06:12:29  2023-09-16 07:51:55
1   소방서5  2023-09-19 06:11:41  2023-09-19 08:08:36
2   소방서1  2023-09-14 06:12:00  2023-09-14 07:24:21
3   소방서6  2023-09-20 06:12:24  2023-09-20 06:30:45
4   소방서9  2023-09-15 06:11:50  2023-09-15 06:44:00
..   ...                  ...                  ...
95  소방서6  2023-09-17 06:12:02  2023-09-17 06:16:49
96  소방서6  2023-09-18 06:12:05  2023-09-18 06:41:31
97  소방서4  2023-09-12 06:11:52  2023-09-12 08:10:19
98  소방서7  2023-09-12 06:12:22  2023-09-12 07:02:26
99  소방서8  2023-09-20 06:12:16  2023-09-20 06:30:46

[100 rows x 3 columns]

In [ ]:
import pandas as pd
# df = pd.read_csv("data6-1-1.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch6/data6-1-1.csv")

# 1) datetime형태로 변경
df['도착시간'] = pd.to_datetime(df['도착시간'])
df['출동시간'] = pd.to_datetime(df['출동시간'])

# 2) 출동시간과 도착시간의 차이를 분으로 계산
df['시간차이(분)'] = (df['도착시간'] - df['출동시간']).dt.total_seconds() / 60

# 3) 소방서별 평균 시간차이 계산
avg_diff = df.groupby('소방서')['시간차이(분)'].mean()

# 4) 평균 차이가 가장 큰 소방서의 시간을 찾고 출력
idx = avg_diff.idxmax()
result = avg_diff[idx]
print(round(result))

81

In [ ]:
# 참고 (시간 반올림)
min = 5.5
print(int(min),"분")
print((min-int(min))*60,"초")

5 분
30.0 초

### 문제2

제공된 데이터셋(df)에서 학교별 학년 데이터(3번째 컬럼부터 끝까지)를 모두 더하여 '총학생수' 파생변수를 생성하시오. 생성된 총학생수를 바탕으로 '교사 한 명당 맡은 학생 수(총학생수 / 교사수)'를 계산하고, 이 값이 가장 큰 학교의 '교사 수'를 정수 형태로 제출하시오.

In [76]:
df['총학생수'] = df.iloc[:, 2:-1].sum(axis = 1)
df

df['ratio'] = df['총학생수']/ df['교사수']
df['ratio'].idxmax()
print(df.loc[df['ratio'].idxmax()]['교사수'])

19

In [61]:
import pandas as pd
# df = pd.read_csv("data6-1-2.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch6/data6-1-2.csv")
df

      학교명  교사수  1학년  2학년  3학년  4학년  5학년  6학년
0     학교1   20  118   72  154  118   77   59
1     학교2   31  187  193  135  137   63   90
2     학교3   23  136  193  135  112   91   50
3     학교4   32   72  146   67   51  130  164
4     학교5   22   61   73   86   82   55  124
..    ...  ...  ...  ...  ...  ...  ...  ...
95   학교96   38   75  166  113  191  172   57
96   학교97   30  125  169  145  122  187  194
97   학교98   37  136  100   93   60  145   63
98   학교99   37   74  175  145  157   95   76
99  학교100   40   68  109  196  148   84  179

[100 rows x 8 columns]

In [ ]:
import pandas as pd
# df = pd.read_csv("data6-1-2.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch6/data6-1-2.csv")

# 1) 총 학생 수 계산
df['총학생수'] = df.iloc[:, 2:].sum(axis=1)

# 2) 교사 한 명당 맡은 학생 수
df['학생/교사'] = df['총학생수'] / df['교사수']

# 3) 학생/교사 최대값의 인덱스명
idx = df['학생/교사'].idxmax()

# 4) 학생/교사 최대값의 학교 교사 수 출력
print(df.loc[idx, '교사수'])

19

In [ ]:
import pandas as pd
# df = pd.read_csv("data6-1-2.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch6/data6-1-2.csv")

# 1) 교사 한 명당 맡은 학생 수
df['학생/교사'] = (df['1학년'] + df['2학년'] + df['3학년'] + df['4학년'] + df['5학년'] + df['6학년']) / df['교사수']

# 2) 학생/교사 컬럼을 내림차순으로 정렬
df = df.sort_values('학생/교사', ascending=False)

# 3) 최상단 행의 교사수 값 출력
print(df.iloc[0, 1])

19

### 문제3

제공된 데이터셋(df)에서 6가지 종류의 범죄 데이터(2번째부터 7번째 컬럼까지)를 모두 더해 '총 범죄 건수' 파생변수를 생성하시오. 날짜 컬럼에서 '연도(앞 4자리)'를 추출한 뒤 연도별 총 범죄 건수의 합계를 구하시오. 연도별 합계 중 가장 큰 값의 월평균 건수(연도 총합 / 12)를 계산하여 반올림한 정수 형태로 제출하시오.

In [96]:
df['연도'] = df['날짜'].str[:4].astype(int)
result = df.groupby('연도')['총 범죄 건수'].sum().max()/12
print(round(result))

533

In [84]:
df['총 범죄 건수'] = df.iloc[:, 1:7].sum(axis = 1)
df

           날짜  강력범죄  절도범죄  폭력범죄  지능범죄  풍속범죄  교통범죄  경찰서명  총 범죄 건수
0   2020년 01월    22   102    86    62    28   212  B경찰서      512
1   2020년 02월    26   138    80    61    31   183  E경찰서      519
2   2020년 03월    14   129    76    60    29   202  C경찰서      510
3   2020년 04월    26   142    83    71    33   182  B경찰서      537
4   2020년 05월    28   131    80    72    28   212  B경찰서      551
5   2020년 06월    22   104    84    72    34   201  A경찰서      517
6   2020년 07월    14   134    84    72    32   182  A경찰서      518
7   2020년 08월    27   101    71    67    31   198  B경찰서      495
8   2020년 09월    21   108    87    70    33   187  B경찰서      506
9   2020년 10월    21   114    89    61    32   212  E경찰서      529
10  2020년 11월    22   134    79    64    35   198  D경찰서      532
11  2020년 12월    13   118    82    76    37   236  C경찰서      562
12  2021년 01월    16   104    82    60    25   206  C경찰서      493
13  2021년 02월    19   145    88    60    30   204  B경찰서      546
14  2021년 03월    12   136    79    72    32   233  B경찰서      564
15  2021년 04월    26   106    87    71    28   216  C경찰서      534
16  2021년 05월    13   140    75    80    29   187  E경찰서      524
17  2021년 06월    12   131    78    65    30   201  E경찰서      517
18  2021년 07월    12   116    79    65    31   202  D경찰서      505
19  2021년 08월    25   129    77    69    33   185  A경찰서      518
20  2021년 09월    28   107    71    71    32   203  D경찰서      512
21  2021년 10월    18   130    71    77    30   206  C경찰서      532
22  2021년 11월    12   140    82    73    32   187  A경찰서      526
23  2021년 12월    27   108    90    89    20   213  E경찰서      547
24  2022년 01월    23   140    83    60    26   219  A경찰서      551
25  2022년 02월    11   111    73    60    31   211  B경찰서      497
26  2022년 03월    17   125    87    76    25   220  C경찰서      550
27  2022년 04월    10   112    78    78    28   185  E경찰서      491
28  2022년 05월    20   122    76    74    30   192  B경찰서      514
29  2022년 06월    24   139    87    77    29   192  E경찰서      548
30  2022년 07월    19   107    79    80    30   193  E경찰서      508
31  2022년 08월    27   124    81    62    29   187  C경찰서      510
32  2022년 09월    25   108    76    66    28   182  B경찰서      485
33  2022년 10월    25   134    71    75    33   189  C경찰서      527
34  2022년 11월    26   122    72    62    31   180  E경찰서      493
35  2022년 12월    22   104    87    80    31   181  C경찰서      505
36  2023년 01월    28   127    90    73    33   202  B경찰서      553
37  2023년 02월    10   102    96    73    33   166  A경찰서      480
38  2023년 03월    29   140    70    79    34   211  C경찰서      563
39  2023년 04월    17   123   100    62    32   201  B경찰서      535
40  2023년 05월    11   138    70    75    35   190  B경찰서      519
41  2023년 06월    30   128    78    74    34   216  C경찰서      560
42  2023년 07월    30   144    74    73    31   248  D경찰서      600
43  2023년 08월    26   120    86    76    33   188  C경찰서      529
44  2023년 09월    11   117    86    65    33   192  C경찰서      504
45  2023년 10월    12   117    86    67    28   200  C경찰서      510
46  2023년 11월    22   103    83    72    33   196  B경찰서      509
47  2023년 12월    28   124    83    61    27   209  A경찰서      532
48  2024년 01월    10   140    90    65    31   184  B경찰서      520
49  2024년 02월    16   137    72    80    30   180  C경찰서      515
50  2024년 03월    17   144    84    76    34   197  C경찰서      552
51  2024년 04월    14   150    85    75    31   181  C경찰서      536
52  2024년 05월    22   119    73    74    34   200  B경찰서      522
53  2024년 06월    30   122    70    70    24   161  B경찰서      477
54  2024년 07월    21   115    76    62    35   151  C경찰서      460
55  2024년 08월    17   104    98    85    24   180  E경찰서      508
56  2024년 09월    21   128    84    69    31   181  B경찰서      514
57  2024년 10월    20   105    80    77    33   188  E경찰서      503
58  2024년 11월    25   148    90    67    33   210  B경찰서      573
59  2024년 12월    21   142    77    62    35   183  E경찰서      520

In [77]:
import pandas as pd
# df = pd.read_csv("data6-1-3.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch6/data6-1-3.csv")
df

           날짜  강력범죄  절도범죄  폭력범죄  지능범죄  풍속범죄  교통범죄  경찰서명
0   2020년 01월    22   102    86    62    28   212  B경찰서
1   2020년 02월    26   138    80    61    31   183  E경찰서
2   2020년 03월    14   129    76    60    29   202  C경찰서
3   2020년 04월    26   142    83    71    33   182  B경찰서
4   2020년 05월    28   131    80    72    28   212  B경찰서
5   2020년 06월    22   104    84    72    34   201  A경찰서
6   2020년 07월    14   134    84    72    32   182  A경찰서
7   2020년 08월    27   101    71    67    31   198  B경찰서
8   2020년 09월    21   108    87    70    33   187  B경찰서
9   2020년 10월    21   114    89    61    32   212  E경찰서
10  2020년 11월    22   134    79    64    35   198  D경찰서
11  2020년 12월    13   118    82    76    37   236  C경찰서
12  2021년 01월    16   104    82    60    25   206  C경찰서
13  2021년 02월    19   145    88    60    30   204  B경찰서
14  2021년 03월    12   136    79    72    32   233  B경찰서
15  2021년 04월    26   106    87    71    28   216  C경찰서
16  2021년 05월    13   140    75    80    29   187  E경찰서
17  2021년 06월    12   131    78    65    30   201  E경찰서
18  2021년 07월    12   116    79    65    31   202  D경찰서
19  2021년 08월    25   129    77    69    33   185  A경찰서
20  2021년 09월    28   107    71    71    32   203  D경찰서
21  2021년 10월    18   130    71    77    30   206  C경찰서
22  2021년 11월    12   140    82    73    32   187  A경찰서
23  2021년 12월    27   108    90    89    20   213  E경찰서
24  2022년 01월    23   140    83    60    26   219  A경찰서
25  2022년 02월    11   111    73    60    31   211  B경찰서
26  2022년 03월    17   125    87    76    25   220  C경찰서
27  2022년 04월    10   112    78    78    28   185  E경찰서
28  2022년 05월    20   122    76    74    30   192  B경찰서
29  2022년 06월    24   139    87    77    29   192  E경찰서
30  2022년 07월    19   107    79    80    30   193  E경찰서
31  2022년 08월    27   124    81    62    29   187  C경찰서
32  2022년 09월    25   108    76    66    28   182  B경찰서
33  2022년 10월    25   134    71    75    33   189  C경찰서
34  2022년 11월    26   122    72    62    31   180  E경찰서
35  2022년 12월    22   104    87    80    31   181  C경찰서
36  2023년 01월    28   127    90    73    33   202  B경찰서
37  2023년 02월    10   102    96    73    33   166  A경찰서
38  2023년 03월    29   140    70    79    34   211  C경찰서
39  2023년 04월    17   123   100    62    32   201  B경찰서
40  2023년 05월    11   138    70    75    35   190  B경찰서
41  2023년 06월    30   128    78    74    34   216  C경찰서
42  2023년 07월    30   144    74    73    31   248  D경찰서
43  2023년 08월    26   120    86    76    33   188  C경찰서
44  2023년 09월    11   117    86    65    33   192  C경찰서
45  2023년 10월    12   117    86    67    28   200  C경찰서
46  2023년 11월    22   103    83    72    33   196  B경찰서
47  2023년 12월    28   124    83    61    27   209  A경찰서
48  2024년 01월    10   140    90    65    31   184  B경찰서
49  2024년 02월    16   137    72    80    30   180  C경찰서
50  2024년 03월    17   144    84    76    34   197  C경찰서
51  2024년 04월    14   150    85    75    31   181  C경찰서
52  2024년 05월    22   119    73    74    34   200  B경찰서
53  2024년 06월    30   122    70    70    24   161  B경찰서
54  2024년 07월    21   115    76    62    35   151  C경찰서
55  2024년 08월    17   104    98    85    24   180  E경찰서
56  2024년 09월    21   128    84    69    31   181  B경찰서
57  2024년 10월    20   105    80    77    33   188  E경찰서
58  2024년 11월    25   148    90    67    33   210  B경찰서
59  2024년 12월    21   142    77    62    35   183  E경찰서

In [ ]:
import pandas as pd
# df = pd.read_csv("data6-1-3.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch6/data6-1-3.csv")

# 1) 총 범죄 건수 계산
df['총 범죄 건수'] = df.iloc[:, 1:7].sum(axis=1)

# 2) 연도 슬라이싱
df['연도'] = df["날짜"].str[:4]

# 3) 연도별 총 범죄 건수 합 계산
result = df['총 범죄 건수'].groupby(df["연도"]).sum()

# 4) 가장 큰 값의 월 평균 계산
print(round(result.max()/12))

533