[구글 코랩(Colab)에서 실행하기](https://colab.research.google.com/github/lovedlim/bigdata_analyst_cert_v2/blob/main/part4/ch6/p6_type1.ipynb)

## 작업형1

### 문제1

In [19]:
df.groupby('소방서')['차이'].mean().max()

80.6588888888889

In [7]:
df

     소방서                출동시간                도착시간              차이
0   소방서1 2023-09-16 06:12:29 2023-09-16 07:51:55 0 days 01:39:26
1   소방서5 2023-09-19 06:11:41 2023-09-19 08:08:36 0 days 01:56:55
2   소방서1 2023-09-14 06:12:00 2023-09-14 07:24:21 0 days 01:12:21
3   소방서6 2023-09-20 06:12:24 2023-09-20 06:30:45 0 days 00:18:21
4   소방서9 2023-09-15 06:11:50 2023-09-15 06:44:00 0 days 00:32:10
..   ...                 ...                 ...             ...
95  소방서6 2023-09-17 06:12:02 2023-09-17 06:16:49 0 days 00:04:47
96  소방서6 2023-09-18 06:12:05 2023-09-18 06:41:31 0 days 00:29:26
97  소방서4 2023-09-12 06:11:52 2023-09-12 08:10:19 0 days 01:58:27
98  소방서7 2023-09-12 06:12:22 2023-09-12 07:02:26 0 days 00:50:04
99  소방서8 2023-09-20 06:12:16 2023-09-20 06:30:46 0 days 00:18:30

[100 rows x 4 columns]

In [17]:
df['출동시간'] = pd.to_datetime(df['출동시간'])
df['도착시간'] = pd.to_datetime(df['도착시간'])
df.info()
df['차이'] = (df['도착시간']-df['출동시간']).dt.total_seconds()/60
df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   소방서     100 non-null    object
 1   출동시간    100 non-null    datetime64[ns]
 2   도착시간    100 non-null    datetime64[ns]
 3   차이      100 non-null    float64
dtypes: datetime64[ns](2), float64(1), object(1)
memory usage: 3.3+ KB

     소방서                출동시간                도착시간          차이
0   소방서1 2023-09-16 06:12:29 2023-09-16 07:51:55   99.433333
1   소방서5 2023-09-19 06:11:41 2023-09-19 08:08:36  116.916667
2   소방서1 2023-09-14 06:12:00 2023-09-14 07:24:21   72.350000
3   소방서6 2023-09-20 06:12:24 2023-09-20 06:30:45   18.350000
4   소방서9 2023-09-15 06:11:50 2023-09-15 06:44:00   32.166667
..   ...                 ...                 ...         ...
95  소방서6 2023-09-17 06:12:02 2023-09-17 06:16:49    4.783333
96  소방서6 2023-09-18 06:12:05 2023-09-18 06:41:31   29.433333
97  소방서4 2023-09-12 06:11:52 2023-09-12 08:10:19  118.450000
98  소방서7 2023-09-12 06:12:22 2023-09-12 07:02:26   50.066667
99  소방서8 2023-09-20 06:12:16 2023-09-20 06:30:46   18.500000

[100 rows x 4 columns]

In [1]:
import pandas as pd
# df = pd.read_csv("data6-1-1.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch6/data6-1-1.csv")
df

     소방서                 출동시간                 도착시간
0   소방서1  2023-09-16 06:12:29  2023-09-16 07:51:55
1   소방서5  2023-09-19 06:11:41  2023-09-19 08:08:36
2   소방서1  2023-09-14 06:12:00  2023-09-14 07:24:21
3   소방서6  2023-09-20 06:12:24  2023-09-20 06:30:45
4   소방서9  2023-09-15 06:11:50  2023-09-15 06:44:00
..   ...                  ...                  ...
95  소방서6  2023-09-17 06:12:02  2023-09-17 06:16:49
96  소방서6  2023-09-18 06:12:05  2023-09-18 06:41:31
97  소방서4  2023-09-12 06:11:52  2023-09-12 08:10:19
98  소방서7  2023-09-12 06:12:22  2023-09-12 07:02:26
99  소방서8  2023-09-20 06:12:16  2023-09-20 06:30:46

[100 rows x 3 columns]

In [ ]:
import pandas as pd
# df = pd.read_csv("data6-1-1.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch6/data6-1-1.csv")

# 1) datetime형태로 변경
df['도착시간'] = pd.to_datetime(df['도착시간'])
df['출동시간'] = pd.to_datetime(df['출동시간'])

# 2) 출동시간과 도착시간의 차이를 분으로 계산
df['시간차이(분)'] = (df['도착시간'] - df['출동시간']).dt.total_seconds() / 60

# 3) 소방서별 평균 시간차이 계산
avg_diff = df.groupby('소방서')['시간차이(분)'].mean()

# 4) 평균 차이가 가장 큰 소방서의 시간을 찾고 출력
idx = avg_diff.idxmax()
result = avg_diff[idx]
print(round(result))

81

In [ ]:
# 참고 (시간 반올림)
min = 5.5
print(int(min),"분")
print((min-int(min))*60,"초")

5 분
30.0 초

### 문제2

In [27]:
df['ratio'] = df['총학생수']/df['교사수']
idx = df['ratio'].idxmax()
print(df.loc[idx, '학교명'])
print(df.loc[idx, '교사수'])

학교8
19

In [25]:
df['총학생수'] = df.iloc[:,2:].sum(axis = 1)
df

      학교명  교사수  1학년  2학년  3학년  4학년  5학년  6학년   총학생수
0     학교1   20  118   72  154  118   77   59  598.0
1     학교2   31  187  193  135  137   63   90  805.0
2     학교3   23  136  193  135  112   91   50  717.0
3     학교4   32   72  146   67   51  130  164  630.0
4     학교5   22   61   73   86   82   55  124  481.0
..    ...  ...  ...  ...  ...  ...  ...  ...    ...
95   학교96   38   75  166  113  191  172   57  774.0
96   학교97   30  125  169  145  122  187  194  942.0
97   학교98   37  136  100   93   60  145   63  597.0
98   학교99   37   74  175  145  157   95   76  722.0
99  학교100   40   68  109  196  148   84  179  784.0

[100 rows x 9 columns]

In [20]:
import pandas as pd
# df = pd.read_csv("data6-1-2.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch6/data6-1-2.csv")
df

      학교명  교사수  1학년  2학년  3학년  4학년  5학년  6학년
0     학교1   20  118   72  154  118   77   59
1     학교2   31  187  193  135  137   63   90
2     학교3   23  136  193  135  112   91   50
3     학교4   32   72  146   67   51  130  164
4     학교5   22   61   73   86   82   55  124
..    ...  ...  ...  ...  ...  ...  ...  ...
95   학교96   38   75  166  113  191  172   57
96   학교97   30  125  169  145  122  187  194
97   학교98   37  136  100   93   60  145   63
98   학교99   37   74  175  145  157   95   76
99  학교100   40   68  109  196  148   84  179

[100 rows x 8 columns]

In [ ]:
import pandas as pd
# df = pd.read_csv("data6-1-2.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch6/data6-1-2.csv")

# 1) 총 학생 수 계산
df['총학생수'] = df.iloc[:, 2:].sum(axis=1)

# 2) 교사 한 명당 맡은 학생 수
df['학생/교사'] = df['총학생수'] / df['교사수']

# 3) 학생/교사 최대값의 인덱스명
idx = df['학생/교사'].idxmax()

# 4) 학생/교사 최대값의 학교 교사 수 출력
print(df.loc[idx, '교사수'])

19

In [ ]:
import pandas as pd
# df = pd.read_csv("data6-1-2.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch6/data6-1-2.csv")

# 1) 교사 한 명당 맡은 학생 수
df['학생/교사'] = (df['1학년'] + df['2학년'] + df['3학년'] + df['4학년'] + df['5학년'] + df['6학년']) / df['교사수']

# 2) 학생/교사 컬럼을 내림차순으로 정렬
df = df.sort_values('학생/교사', ascending=False)

# 3) 최상단 행의 교사수 값 출력
print(df.iloc[0, 1])

19

### 문제3

In [ ]:
import pandas as pd
# df = pd.read_csv("data6-1-3.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch6/data6-1-3.csv")

# 1) 총 범죄 건수 계산
df['총 범죄 건수'] = df.iloc[:, 1:7].sum(axis=1)

# 2) 연도 슬라이싱
df['연도'] = df["날짜"].str[:4]

# 3) 연도별 총 범죄 건수 합 계산
result = df['총 범죄 건수'].groupby(df["연도"]).sum()

# 4) 가장 큰 값의 월 평균 계산
print(round(result.max()/12))

533