[구글 코랩(Colab)에서 실행하기](https://colab.research.google.com/github/lovedlim/bigdata_analyst_cert_v2/blob/main/part4/ch7/p7_type3.ipynb)

## 작업형3

### 문제1-1

분할한 train 데이터(210행까지 train)를 바탕으로 gender를 종속변수로, weight를 유일한 독립변수로 설정하여 로지스틱 회귀분석을 수행하시오. 이 모델을 바탕으로 weight(무게)가 1단위 증가할 때의 오즈비(Odds Ratio, 승산비)를 구하시오.

출력 형식: 소수점 넷째 자리까지 반올림 (예: 1.2345)

In [9]:
df.iloc[:210]

     age    length  diameter    height     weight  gender
0      6  0.474627  0.211352  0.178189  78.971766       1
1      1  0.465847  0.339388  0.170522  98.781960       1
2      4  0.122807  0.238691  0.106924  88.792625       0
3      4  0.204579  0.360543  0.034261   1.028847       0
4      8  0.243458  0.358037  0.128080   6.503367       0
..   ...       ...       ...       ...        ...     ...
205    3  0.166407  0.275287  0.053562  10.984565       0
206    6  0.287122  0.177562  0.140229  96.468826       1
207    6  0.262202  0.283700  0.110018  71.407627       1
208    1  0.440058  0.250145  0.114510  52.637451       0
209    9  0.497767  0.321139  0.168125  88.668743       0

[210 rows x 6 columns]

In [10]:
train = df.iloc[:210]

import statsmodels.formula.api as smf
formula = "gender ~ weight "
model = smf.logit(formula, data = train).fit()
print(model.summary())

import numpy as np
coef = model.params['weight']
print(round(np.exp(coef),4))

Optimization terminated successfully.
         Current function value: 0.690045
         Iterations 4
                           Logit Regression Results
==============================================================================
Dep. Variable:                 gender   No. Observations:                  210
Model:                          Logit   Df Residuals:                      208
Method:                           MLE   Df Model:                            1
Date:                Tue, 16 Jun 2026   Pseudo R-squ.:                0.003431
Time:                        13:37:20   Log-Likelihood:                -144.91
converged:                       True   LL-Null:                       -145.41
Covariance Type:            nonrobust   LLR p-value:                    0.3178
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     -0.3140      0.276     -1.137      0.256      -0.855       0.227
weight         0.0047      0.005      0.997      0.319      -0.005       0.014
==============================================================================
1.0047

In [4]:
import pandas as pd
# df = pd.read_csv("clam.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch7/clam.csv")
df

     age    length  diameter    height     weight  gender
0      6  0.474627  0.211352  0.178189  78.971766       1
1      1  0.465847  0.339388  0.170522  98.781960       1
2      4  0.122807  0.238691  0.106924  88.792625       0
3      4  0.204579  0.360543  0.034261   1.028847       0
4      8  0.243458  0.358037  0.128080   6.503367       0
..   ...       ...       ...       ...        ...     ...
295    3  0.559766  0.390519  0.079062  57.877344       0
296    8  0.371229  0.355306  0.040285  31.909257       1
297    2  0.595571  0.104829  0.132500   4.924550       1
298    7  0.291551  0.289444  0.073238  51.474851       0
299    6  0.503335  0.061925  0.187127   6.850624       1

[300 rows x 6 columns]

In [ ]:
import pandas as pd
# df = pd.read_csv("clam.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch7/clam.csv")

# 데이터셋 분할
print(df.shape)
train = df.iloc[:210]
test = df.iloc[210:]
print(train.shape)

print(train.head())

(300, 6)
(210, 6)
   age    length  diameter    height     weight  gender
0    6  0.474627  0.211352  0.178189  78.971766       1
1    1  0.465847  0.339388  0.170522  98.781960       1
2    4  0.122807  0.238691  0.106924  88.792625       0
3    4  0.204579  0.360543  0.034261   1.028847       0
4    8  0.243458  0.358037  0.128080   6.503367       0

In [5]:
from statsmodels.formula.api import logit
import numpy as np

# 1) 로지스틱 회귀 모델 생성 및 학습
model = logit("gender ~ weight", data=train).fit()

# 2) 오즈비 계산
odds_ratio = np.exp(model.params['weight'])
print(round(odds_ratio, 4))

NameError: name 'train' is not defined

### 문제1-2

분할한 train 데이터를 바탕으로 gender를 종속변수로 하고, 5개 변수 전체(age, length, diameter, height, weight)를 독립변수로 설정하여 로지스틱 회귀 모델을 재학습시키시오. 이 모델의 잔차 이탈도(Residual Deviance)를 구하시오.

In [11]:
train.head(2)

   age    length  diameter    height     weight  gender
0    6  0.474627  0.211352  0.178189  78.971766       1
1    1  0.465847  0.339388  0.170522  98.781960       1

In [13]:
model = smf.logit("gender~ age + length + diameter + height + weight", data = train).fit()
print(model.summary())
print(model.llf *-2)

Optimization terminated successfully.
         Current function value: 0.683173
         Iterations 4
                           Logit Regression Results
==============================================================================
Dep. Variable:                 gender   No. Observations:                  210
Model:                          Logit   Df Residuals:                      204
Method:                           MLE   Df Model:                            5
Date:                Tue, 16 Jun 2026   Pseudo R-squ.:                 0.01336
Time:                        13:40:29   Log-Likelihood:                -143.47
converged:                       True   LL-Null:                       -145.41
Covariance Type:            nonrobust   LLR p-value:                    0.5662
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      0.6701      0.651      1.030      0.303      -0.605       1.946
age           -0.0482      0.055     -0.881      0.378      -0.156       0.059
length        -0.7832      0.998     -0.785      0.433      -2.739       1.173
diameter      -1.1573      1.389     -0.833      0.405      -3.880       1.565
height        -2.2977      2.640     -0.870      0.384      -7.472       2.877
weight         0.0054      0.005      1.098      0.272      -0.004       0.015
==============================================================================
286.93267518507366

In [ ]:
# 1) 로지스틱 회귀 모델 생성 및 학습
formula = "gender ~ age + length + diameter + height + weight"
model = logit(formula, data=train).fit()

# 2) 잔차이탈도
print(round(-2 * model.llf,2))

Optimization terminated successfully.
         Current function value: 0.683173
         Iterations 4
286.93

### 문제1-3

[문제 1-1]에서 학습시킨 단일 변수(weight) 로지스틱 회귀 모델을 사용하되, test 데이터의 gender 값을 예측하시오. 예측된 확률 값이 0.5를 초과(이상)하는 경우 1, 그렇지 않은 경우 0으로 분류했을 때의 오류율을 구하시오

출력형식 셋째자리

In [16]:
test = df[210:]

import statsmodels.formula.api as smf
formula = "gender ~ weight "
model = smf.logit(formula, data = train).fit()
pred = model.predict(test)
print((pred > 0.5).astype(int))

Optimization terminated successfully.
         Current function value: 0.690045
         Iterations 4
210    1
211    1
212    1
213    1
214    0
      ..
295    0
296    0
297    0
298    0
299    0
Length: 90, dtype: int64

In [21]:
from sklearn.metrics import accuracy_score
prediction = (pred > 0.5).astype(int)
error_rate = 1 - accuracy_score(test['gender'], prediction)
print(round(error_rate,3))

0.478

In [ ]:
from sklearn.metrics import accuracy_score

# 1) test데이터를 사용해 예측 (0.5 미만: 0, 0.5 이상 1)
model = logit("gender ~ weight", data=train).fit()
target = test.pop('gender')
pred = model.predict(test)
pred = (pred > 0.5).astype(int)

# 2) 실제 값과 예측값을 사용하여 정확도 계산
accuracy = accuracy_score(target, pred)

# 3) 오류율 계산
error_rate = 1 - accuracy
print(round(error_rate, 3))
# 0.478

Optimization terminated successfully.
         Current function value: 0.690045
         Iterations 4
0.478

### 문제2-1

제공된 데이터셋(df) 전체를 사용하여 모든 수치형 변수 간의 피어슨 상관계수를 구하시오. 이 중 ERP 변수와 다른 변수들 간의 상관계수 중 가장 큰 값(단, ERP 자기 자신과의 상관계수 1은 제외)을 구하시오.

출력 형식: 소수점 몇째 자리까지 반올림 (예: 0.854)

In [24]:
import pandas as pd

# df = pd.read_csv("system_cpu.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch7/system_cpu.csv")
df.corr()

               ERP  Feature1  Feature2  Feature3       CPU
ERP       1.000000 -0.053848  0.092432  0.882194  0.092455
Feature1 -0.053848  1.000000 -0.020095 -0.015767  0.023664
Feature2  0.092432 -0.020095  1.000000  0.118877  0.130492
Feature3  0.882194 -0.015767  0.118877  1.000000  0.137120
CPU       0.092455  0.023664  0.130492  0.137120  1.000000

In [27]:
df_corr = df.corr()
print(round(df_corr['ERP'][1:].max(),3))

0.882

In [ ]:
import pandas as pd

# df = pd.read_csv("system_cpu.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch7/system_cpu.csv")

print(df.head())

     ERP  Feature1  Feature2  Feature3    CPU
0   30.6     235.1      44.5      44.0  112.3
1   40.3      36.6      46.4      36.1   58.6
2   57.7      52.2      66.5       2.0   55.3
3  128.3     196.2      59.8      57.4  103.2
4   80.3      75.2      59.6      58.2  104.1

In [ ]:
import pandas as pd
# df = pd.read_csv("system_cpu.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch7/system_cpu.csv")

# 1) ERP와 각 변수 사이의 상관계수 계산
corr_matrix = df.corr()

# 2) ERP와 다른 변수들과의 상관계수 출력
erp_corr = corr_matrix['ERP'].sort_values(ascending=False)
print(erp_corr)

ERP         1.000000
Feature3    0.882194
CPU         0.092455
Feature2    0.092432
Feature1   -0.053848
Name: ERP, dtype: float64

### 문제2-2, 2-3

문제 2-2]
데이터셋에서 CPU 변수의 값이 100 미만인 데이터만 필터링하여 분석을 진행하시오. 필터링된 데이터를 바탕으로 ERP를 종속변수로 하고, Feature1, Feature2, Feature3, CPU를 독립변수로 설정하여 다중선형회귀분석을 수행하시오. 분석 결과 중 회귀 모델의 요약 정보(Summary)를 확인하여 문제를 해결하시오.
(주로 이 단계에서 특정 변수의 회귀계수, p-value, 또는 결정계수 등을 최종 값으로 요구합니다.)

In [30]:
df1 = df[df['CPU'] < 100]
df1

import statsmodels.formula.api as smf
formula = "ERP ~ Feature1 + Feature2 + Feature3 + CPU"
model = smf.ols(formula, data = df1).fit()
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                    ERP   R-squared:                       0.755
Model:                            OLS   Adj. R-squared:                  0.736
Method:                 Least Squares   F-statistic:                     39.30
Date:                Tue, 16 Jun 2026   Prob (F-statistic):           5.36e-15
Time:                        14:24:34   Log-Likelihood:                -260.40
No. Observations:                  56   AIC:                             530.8
Df Residuals:                      51   BIC:                             540.9
Df Model:                           4
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     51.4133     19.112      2.690      0.010      13.045      89.782
Feature1      -0.0242      0.059     -0.409      0.684      -0.143       0.094
Feature2       0.0602      0.106      0.569      0.572      -0.152       0.273
Feature3       1.4126      0.113     12.458      0.000       1.185       1.640
CPU           -0.4651      0.234     -1.985      0.053      -0.936       0.005
==============================================================================
Omnibus:                        3.758   Durbin-Watson:                   1.762
Prob(Omnibus):                  0.153   Jarque-Bera (JB):                2.757
Skew:                           0.436   Prob(JB):                        0.252
Kurtosis:                       3.648   Cond. No.                         780.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [ ]:
from statsmodels.formula.api import ols

# 1) CPU가 100 미만인 데이터 필터링
filtered_df = df[df['CPU'] < 100]

# 2) 선형회귀 모델 생성: ERP를 종속 변수로, 나머지 변수들을 독립 변수로 설정
model = ols('ERP ~ Feature1 + Feature2 + Feature3 + CPU', data=filtered_df).fit()

# 3) 모델 요약 정보 출력
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                    ERP   R-squared:                       0.755
Model:                            OLS   Adj. R-squared:                  0.736
Method:                 Least Squares   F-statistic:                     39.30
Date:                Mon, 17 Mar 2025   Prob (F-statistic):           5.36e-15
Time:                        03:44:38   Log-Likelihood:                -260.40
No. Observations:                  56   AIC:                             530.8
Df Residuals:                      51   BIC:                             540.9
Df Model:                           4
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     51.4133     19.112      2.690      0.010      13.045      89.782
Feature1      -0.0242      0.059     -0.409      0.684      -0.143       0.094
Feature2       0.0602      0.106      0.569      0.572      -0.152       0.273
Feature3       1.4126      0.113     12.458      0.000       1.185       1.640
CPU           -0.4651      0.234     -1.985      0.053      -0.936       0.005
==============================================================================
Omnibus:                        3.758   Durbin-Watson:                   1.762
Prob(Omnibus):                  0.153   Jarque-Bera (JB):                2.757
Skew:                           0.436   Prob(JB):                        0.252
Kurtosis:                       3.648   Cond. No.                         780.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.